# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/erpc.yaml.j2

erpc:
  fullnameOverride: erpc
  image:
    repository: ghcr.io/erpc/erpc
    tag: 0.0.49
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: rpc.dc-devnet-0.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  config: |
    logLevel: info

    database:
      evmJsonRpcCache:
        connectors:
          - id: memory-cache
            driver: memory # Refer to "memory" driver docs below
            memory:
              maxItems: 100000
        policies:
          # Cache all methods with finalized data including empty responses
          - network: "*"
            method: "*"
            finality: finalized
            empty: allow
            connector: memory-cache
            ttl: 0
          # Cache unfinalized data only for 5 seconds (getLogs of a recent block) except empty responses
          - network: "*"
            method: "*"
            finality: unfinalized
            empty: ignore
            connector: memory-cache
            ttl: 5s
          # Cache unknown finalization data (eth_trace*) only for 10 seconds
          - network: "*"
            method: "*"
            finality: unknown
            empty: ignore
            connector: memory-cache
            ttl: 10s
          # Cache realtime data only for 2 seconds (eth_blockNumber, eth_gasPrice, etc) to reduce costs yet fresh enough data
          - network: "*"
            method: "*"
            finality: realtime
            empty: ignore
            connector: memory-cache
            ttl: 2s

    server:
      httpHostV4: "0.0.0.0"
      listenV6: true
      httpHostV6: "[::]"
      httpPort: 4000
      aliasing:
        rules:
          - matchDomain: "*"
            serveProject: "main"
            serveArchitecture: "evm"
            serveChain: "708482336"

    metrics:
      enabled: true
      hostV4: "0.0.0.0"
      hostV6: "[::]"
      port: 4001

    projects:
      - id: main
        cors:
          allowedOrigins:
            - "https://*.ethpandaops.io"
          allowedMethods: 
            - "GET"
            - "POST"
            - "OPTIONS"
          allowedHeaders:
            - "Content-Type"
        upstreamDefaults:
          allowMethods:
            - "eth_blockNumber"
            - "eth_call"
            - "eth_chainId"
            - "eth_config"
            - "eth_estimateGas"
            - "eth_feeHistory"
            - "eth_blobBaseFee"
            - "eth_gasPrice"
            - "eth_getBlockAccessList"
            - "eth_getBlockAccessListByHash"
            - "eth_getBlockAccessListByNumber"
            - "eth_getBalance"
            - "eth_getBlockByHash"
            - "eth_getBlockByNumber"
            - "eth_getBlockReceipts"
            - "eth_getBlockTransactionCountByHash"
            - "eth_getBlockTransactionCountByNumber"
            - "eth_getCode"
            - "eth_getFilterChanges"
            - "eth_getLogs"
            - "eth_getStorageAt"
            - "eth_getTransactionByBlockHashAndIndex"
            - "eth_getTransactionByBlockNumberAndIndex"
            - "eth_getTransactionByHash"
            - "eth_getTransactionCount"
            - "eth_getTransactionReceipt"
            - "eth_getProof"
            - "eth_newBlockFilter"
            - "eth_newPendingTransactionFilter"
            - "eth_maxPriorityFeePerGas"
            - "eth_sendRawTransaction"
            - "eth_subscribe"
            - "eth_syncing"
            - "eth_uninstallFilter"
            - "eth_unsubscribe"
            - "net_listening"
            - "net_version"
            - "rpc_modules"
            - "web3_clientVersion"
            - "debug_getRawReceipts"
            - "debug_traceBlock"
            - "trace_transaction"
            - "trace_block"
        upstreams:
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-bootnode-1.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-1.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-10.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-11.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-12.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-13.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-14.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-15.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-16.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-17.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-18.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-19.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-2.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-20.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-21.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-22.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-23.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-24.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-25.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-26.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-27.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-28.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-29.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-3.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-30.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-31.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-32.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-33.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-34.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-35.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-36.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-37.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-38.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-39.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-4.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-40.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-41.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-42.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-43.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-44.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-45.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-46.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-47.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-48.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-49.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-5.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-50.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-6.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-7.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-8.srv.dc-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dc-devnets.node_ingress.combined}>@rpc-prysm-geth-9.srv.dc-devnet-0.ethpandaops.io
