# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-cl.yaml.j2
# Consensus layer endpoints

- url: https://bn-bootnode-1.srv.dc-devnet-0.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-1.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-1
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-10.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-10
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-11.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-11
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-12.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-12
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-13.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-13
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-14.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-14
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-15.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-15
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-16.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-16
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-17.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-17
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-18.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-18
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-19.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-19
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-2.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-2
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-20.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-20
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-21.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-21
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-22.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-22
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-23.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-23
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-24.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-24
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-25.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-25
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-26.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-26
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-27.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-27
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-28.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-28
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-29.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-29
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-3.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-3
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-30.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-30
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-31.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-31
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-32.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-32
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-33.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-33
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-34.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-34
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-35.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-35
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-36.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-36
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-37.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-37
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-38.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-38
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-39.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-39
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-4.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-4
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-40.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-40
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-41.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-41
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-42.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-42
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-43.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-43
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-44.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-44
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-45.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-45
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-46.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-46
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-47.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-47
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-48.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-48
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-49.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-49
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-5.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-5
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-50.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-50
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-6.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-6
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-7.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-7
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-8.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-8
  authGroup: pandaops
  priority: -1
- url: https://bn-prysm-geth-9.srv.dc-devnet-0.ethpandaops.io
  name: prysm-geth-9
  authGroup: pandaops
  priority: -1

