xatu-mimicry:
  enabled: true
  fullnameOverride: xatu-mimicry
  image:
    repository: ethpandaops/xatu
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    name: "dc-devnet-1-xatu-mimicry"
    captureDelay: 3m
    ntpServer: time.google.com
    ethereum:
      overrideNetworkName: "dc-devnet-1"
    coordinator:
      type: static
      config:
        retryInterval: 60s
        nodeRecords:
          - enode://4aed10eec62a6e1a7d85128c1a8f9c153e11914016519ada1852232d70408d058d384c4e1ba0164958ec57f99d1b90d441117df51993068d12693ee89b09ba18@143.110.145.175:30303?discport=30303
    outputs:
    - name: grpc
      type: xatu
      config:
        address: server.xatu-experimental.ethpandaops.io:443
        maxQueueSize: 51200
        tls: true
        headers:
          authorization: "Basic <path:/secrets/services/services.enc.yaml#xatu | jsonPath {.experimental.event_ingester_auth}>"
        batchTimeout: 5s
        exportTimeout: 30s
        maxExportBatchSize: 512
